[tox]
envlist = lint

[testenv:reformat]
commands =
    ruff format .
    ruff check --select I --fix .
allowlist_externals =
    ruff
skip_install = true

[testenv:lint]
description = check code style
commands =
    ruff format --check .
    ruff check .
skip_install = true
allowlist_externals =
    ruff
